### ISSUE TITLE
Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

### ISSUE THREAD

**Issue by sonalpriya17** [sonalpriya17/Sonal_17#1]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1484630510012,"updateDate":1484630510012,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.2","maxVersion":"47.0.2"}],"targetPlatforms":[],"seen":true}
1484631487690	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1484631487692	DeferredSave.extensions.json	DEBUG	Save changes
1484631487692	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1484631487693	addons.xpi-utils	DEBUG	Updating add-on states
1484631487695	addons.xpi-utils	DEBUG	Writing add-ons list
1484631487727	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1484631487728	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1484631487728	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1484631487730	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1484631487732	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1484631487735	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1484631487786	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\websensehelper@mozilla.org.xpi
1484631487787	addons.xpi	DEBUG	Calling bootstrap method startup on websensehelper@mozilla.org version 1.0
1484631487791	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1484631487791	addons.manager	DEBUG	Provider finished startup: XPIProvider
1484631487791	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1484631487791	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1484631487792	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1484631487793	addons.manager	DEBUG	Starting provider: GMPProvider
1484631487818	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1484631487819	addons.manager	DEBUG	Provider finished startup: GMPProvider
1484631487819	addons.manager	DEBUG	Starting provider: PluginProvider
1484631487819	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1484631487824	addons.manager	DEBUG	Provider finished startup: PluginProvider
1484631487825	addons.manager	DEBUG	Completed startup sequence
1484631490135	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1484631490135	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1484631490136	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1484631490598	DeferredSave.extensions.json	DEBUG	Write succeeded
1484631490600	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1484631490600	DeferredSave.extensions.json	DEBUG	Starting timer
1484631490623	DeferredSave.extensions.json	DEBUG	Starting write
1484631490655	addons.repository	DEBUG	No addons.json found.
1484631490656	DeferredSave.addons.json	DEBUG	Save changes
1484631490661	DeferredSave.addons.json	DEBUG	Starting timer
1484631490747	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1484631490747	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1484631490748	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1484631490778	DeferredSave.addons.json	DEBUG	Starting write
1484631490782	DeferredSave.extensions.json	DEBUG	Write succeeded
1484631491095	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at mypackage.practice1.main(practice1.java:17)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1484630510012,"updateDate":1484630510012,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.2","maxVersion":"47.0.2"}],"targetPlatforms":[],"seen":true}
1484631487690	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1484631487692	DeferredSave.extensions.json	DEBUG	Save changes
1484631487692	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1484631487693	addons.xpi-utils	DEBUG	Updating add-on states
1484631487695	addons.xpi-utils	DEBUG	Writing add-ons list
1484631487727	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1484631487728	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1484631487728	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1484631487730	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1484631487732	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1484631487735	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1484631487786	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\websensehelper@mozilla.org.xpi
1484631487787	addons.xpi	DEBUG	Calling bootstrap method startup on websensehelper@mozilla.org version 1.0
1484631487791	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1484631487791	addons.manager	DEBUG	Provider finished startup: XPIProvider
1484631487791	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1484631487791	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1484631487792	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1484631487793	addons.manager	DEBUG	Starting provider: GMPProvider
1484631487818	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1484631487819	addons.manager	DEBUG	Provider finished startup: GMPProvider
1484631487819	addons.manager	DEBUG	Starting provider: PluginProvider
1484631487819	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1484631487824	addons.manager	DEBUG	Provider finished startup: PluginProvider
1484631487825	addons.manager	DEBUG	Completed startup sequence
1484631490135	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1484631490135	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1484631490136	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1484631490598	DeferredSave.extensions.json	DEBUG	Write succeeded
1484631490600	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1484631490600	DeferredSave.extensions.json	DEBUG	Starting timer
1484631490623	DeferredSave.extensions.json	DEBUG	Starting write
1484631490655	addons.repository	DEBUG	No addons.json found.
1484631490656	DeferredSave.addons.json	DEBUG	Save changes
1484631490661	DeferredSave.addons.json	DEBUG	Starting timer
1484631490747	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1484631490747	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1484631490748	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1484631490778	DeferredSave.addons.json	DEBUG	Starting write
1484631490782	DeferredSave.extensions.json	DEBUG	Write succeeded
1484631491095	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'BLRKEC398912D', ip: '10.68.177.144', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_77'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:124)
	at mypackage.practice1.main(practice1.java:17)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1484630510012,"updateDate":1484630510012,"applyBackgroundUpdates":1,"skinnable":true,"size":22012,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0.2","maxVersion":"47.0.2"}],"targetPlatforms":[],"seen":true}
1484631487690	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1484631487692	DeferredSave.extensions.json	DEBUG	Save changes
1484631487692	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1484631487693	addons.xpi-utils	DEBUG	Updating add-on states
1484631487695	addons.xpi-utils	DEBUG	Writing add-ons list
1484631487727	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1484631487728	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1484631487728	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1484631487730	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1484631487732	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\loop@mozilla.org.xpi
1484631487735	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2
1484631487786	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\websensehelper@mozilla.org.xpi
1484631487787	addons.xpi	DEBUG	Calling bootstrap method startup on websensehelper@mozilla.org version 1.0
1484631487791	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1484631487791	addons.manager	DEBUG	Provider finished startup: XPIProvider
1484631487791	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1484631487791	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1484631487792	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1484631487793	addons.manager	DEBUG	Starting provider: GMPProvider
1484631487818	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1484631487819	addons.manager	DEBUG	Provider finished startup: GMPProvider
1484631487819	addons.manager	DEBUG	Starting provider: PluginProvider
1484631487819	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1484631487824	addons.manager	DEBUG	Provider finished startup: PluginProvider
1484631487825	addons.manager	DEBUG	Completed startup sequence
1484631490135	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1484631490135	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1484631490136	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1484631490598	DeferredSave.extensions.json	DEBUG	Write succeeded
1484631490600	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1484631490600	DeferredSave.extensions.json	DEBUG	Starting timer
1484631490623	DeferredSave.extensions.json	DEBUG	Starting write
1484631490655	addons.repository	DEBUG	No addons.json found.
1484631490656	DeferredSave.addons.json	DEBUG	Save changes
1484631490661	DeferredSave.addons.json	DEBUG	Starting timer
1484631490747	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1484631490747	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1484631490748	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1484631490778	DeferredSave.addons.json	DEBUG	Starting write
1484631490782	DeferredSave.extensions.json	DEBUG	Write succeeded
1484631491095	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by sonalpriya17** [comment]
package mypackage;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class BangaloreWiki {

	public static void main(String[] args) throws InterruptedException {
		WebDriver driver = new FirefoxDriver();
		// setting path to web driver
		System.setProperty("webdriver.gecko.driver","D:\\SELENIUM\\Gecodriver\\geckodriver.exe");
		Thread.sleep(2000);
		String baseUrl = "https://www.flipkart.com/";
		//String expectedTitle = "WIKIPEDIA";
		driver.get(baseUrl); //launch driver and direct it to base Url
		String actualTitle= "";
		actualTitle = driver.getPageSource() ;
//		if (actualTitle.contentEquals(expectedTitle))
//		{
//			System.out.println("wiki page is bangalore");	
//		}			
//		else
//		{
			System.out.println(actualTitle);;
		}
		
		
	

	}


selenium version :2.53.0
firefox:47.0.2
